# .github/workflows/get-repo-and-owner-ids.yml
name: Get Repo & Owner IDs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  fetch_ids:
    name: Fetch IDs
    runs-on: ubuntu-latest
    # Minimal permissions to read repository metadata via GITHUB_TOKEN
    permissions:
      contents: read
    outputs:
      repository_id: ${{ steps.repo.outputs.repo_id }}
      owner_id: ${{ steps.repo.outputs.owner_id }}
    steps:
      - name: Query GitHub REST API for repository metadata
        id: repo
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_
